FORMAT: 1A

# Weary Examiner
This documentation describes the HTTP API available in the Weary Examiner project.

# Group Sessions
Lists and creates Debug Sessions.

## Session Collection [/session]

### List all Sessions [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "created": "11/05/2014 13:48:27"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Session [POST]
+ Request (application/json)

    + Header
        
            Bearer: a83e4586faed9348df9238
    
    + Body

            { "created": "11/23/2014 15:12:41" }

+ Response 201 (application/json)

        { "id": 3, "created": "11/23/2014 15:12:41" }

## Session [/session/{id}]
A single Session object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
